import express from 'express';
import DayPlan from '../models/DayPlan.js';
import Task from '../models/Task.js';
import protect from '../middleware/auth.js';
import { todayString, isTaskScheduledOnDate } from '../utils/dateHelpers.js';

const router = express.Router();
router.use(protect);

router.get('/:date', async (req, res) => {
  try {
    let plan = await DayPlan.findOne({ user: req.user._id, date: req.params.date }).populate('tasks');
    if (!plan) {
      // Auto-generate based on recurrence
      const allTasks = await Task.find({ user: req.user._id, isActive: true });
      const todayTasks = allTasks.filter(t => isTaskScheduledOnDate(t, req.params.date));
      plan = { date: req.params.date, tasks: todayTasks, isLocked: false, autoGenerated: true };
    }
    res.json(plan);
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

router.post('/', async (req, res) => {
  try {
    const { date, taskIds, note } = req.body;
    const plan = await DayPlan.findOneAndUpdate(
      { user: req.user._id, date },
      { tasks: taskIds, note, isLocked: true },
      { upsert: true, new: true }
    ).populate('tasks');
    res.json(plan);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

export default router;
