import express from 'express';
import DayPlan from '../models/DayPlan.js';
import Task from '../models/Task.js';
import protect from '../middleware/auth.js';
import { isTaskScheduledOnDate } from '../utils/dateHelpers.js';

const router = express.Router();
router.use(protect);

// GET plan for a specific date
router.get('/:date', async (req, res) => {
  try {
    const { date } = req.params;
    // Check if user has a manually locked plan
    const existing = await DayPlan.findOne({
      user: req.user._id,
      date,
    }).populate('tasks');

    if (existing && existing.isLocked) {
      return res.json({ ...existing.toObject(), autoGenerated: false });
    }

    // Auto-generate from recurrence rules
    const allTasks = await Task.find({ user: req.user._id, isActive: true });
    const todayTasks = allTasks.filter(t => isTaskScheduledOnDate(t, date));
    return res.json({
      date,
      tasks: todayTasks,
      isLocked: false,
      autoGenerated: true,
    });
  } catch (err) {
    res.status(500).json({ message: err.message });
  }
});

// POST — lock in a day plan
router.post('/', async (req, res) => {
  try {
    const { date, taskIds, note } = req.body;
    const plan = await DayPlan.findOneAndUpdate(
      { user: req.user._id, date },
      { tasks: taskIds, note, isLocked: true },
      { upsert: true, new: true }
    ).populate('tasks');
    res.json(plan);
  } catch (err) {
    res.status(400).json({ message: err.message });
  }
});

// DELETE a locked plan (reset to auto)
router.delete('/:date', async (req, res) => {
  await DayPlan.findOneAndDelete({ user: req.user._id, date: req.params.date });
  res.json({ message: 'Plan reset' });
});

export default router;